call plug#begin('~/.vim/plugged')

" Elixir
Plug 'slashmili/alchemist.vim'
Plug 'elixir-lang/vim-elixir'
Plug 'mhinz/vim-mix-format'

" UI
Plug 'tomasr/molokai'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Git support
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-rhubarb'

call plug#end()

set nocompatible
filetype off
filetype plugin indent on

set ttyfast

if !has('nvim')
set ttymouse=xterm2
set ttyscroll=3
endif

" Always display the status line
set laststatus=2

" Shift to the next round tab stop
set shiftround

" Enable hightlighting of the current line
set cursorline

" Set encoding to UTF-8
set encoding=utf-8

" Automatically reread files
set autoread

" Automatically indent
set autoindent

" Reconfigure backspace key
set backspace=indent,eol,start

" Enable incremental search
set incsearch

" Enable hightlighting results
set hlsearch

" Enable mouse mode
set mouse=a

" Disable error bells
set noerrorbells

" Show linenumbers
set number
set relativenumber
set ruler

" Show incomplete commands
set showcmd

" Disable swap file
set noswapfile

" Disable backup files
set nobackup

" Split vertical windows right to the current windows
set splitright

" Split horizontal windows below to the current windows
set splitbelow

" Automatically execute :write
set autowrite

" Opening a new file when the current buffer has unsaved changes causes
" files to be hidden instead of closed
set hidden

" Use unix formats instead of windows
set fileformats=unix,dos,mac
set noshowmatch
set noshowmode

" Ignore case when searching
set ignorecase

" Ignore case when searching lowecase
set smartcase

set completeopt=menu,menuone
set nocursorcolumn
set nocursorline
set updatetime=300
set pumheight=10
set lazyredraw

" Set tabs
set tabstop=2
set shiftwidth=2
set smarttab
set expandtab

" color
syntax enable
set t_Co=256
set background=dark

let g:molokai_original = 1
let g:rehash256 = 1
colorscheme molokai

" Vim airline configuration
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='hybrid'
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1

" Elixir
let g:mix_format_on_save = 1
let g:mix_format_elixir_bin_path = '~/.asdf/installs/elixir/ref-master/bin'

" Alchemist
let g:alchemist_tag_disable = 1
