call plug#begin('~/.vim/plugged')

" Elixir
Plug 'slashmili/alchemist.vim'
Plug 'elixir-lang/vim-elixir'
Plug 'mhinz/vim-mix-format'

" UI
Plug 'tomasr/molokai'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Git support
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-rhubarb'

call plug#end()

set nocompatible
filetype off
filetype plugin indent on

set ttyfast

if !has('nvim')
set ttymouse=xterm2
set ttyscroll=3
endif

set laststatus=2
set encoding=utf-8
set autoread
set autoindent
set backspace=indent,eol,start
set incsearch
set hlsearch
set mouse=a
set noerrorbells
set number
set showcmd
set noswapfile
set nobackup
set splitright
set splitbelow
set autowrite
set hidden
set fileformats=unix,dos,mac
set noshowmatch
set noshowmode
set ignorecase
set smartcase
set completeopt=menu,menuone
set nocursorcolumn
set nocursorline
set updatetime=300
set pumheight=10
set lazyredraw

" color
syntax enable
set t_Co=256
set background=dark

let g:molokai_original = 1
let g:rehash256 = 1
colorscheme molokai

" Vim airline configuration
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='hybrid'
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1

" Elixir
let g:mix_format_on_save = 1
let g:mix_format_elixir_bin_path = '~/.asdf/installs/elixir/ref-master/bin'

" Alchemist
let g:alchemist_tag_disable = 1
